import {test,expect} from 'vitest';import {render,screen} from '@testing-library/react';import userEvent from '@testing-library/user-event';import {MemoryRouter} from 'react-router-dom';import {HelmetProvider} from 'react-helmet-async';import App from './App';
const view=(path='/')=>render(<HelmetProvider><MemoryRouter initialEntries={[path]}><App/></MemoryRouter></HelmetProvider>);
test('mobile navigation toggles',async()=>{view();const b=screen.getByRole('button',{name:/menu/i});expect(b).toHaveAttribute('aria-expanded','false');await userEvent.click(b);expect(b).toHaveAttribute('aria-expanded','true')});
test('workflow filtering works',async()=>{view('/workflows');await userEvent.click(screen.getByRole('button',{name:'BuddyGet'}));expect(screen.getByText('BuddyGet Privacy-Aware Compatibility Matcher')).toBeInTheDocument();expect(screen.getByText('BuddyGet Weekly D1 Backup')).toBeInTheDocument();expect(screen.queryByText('Job Application Tracker & HR Routing')).not.toBeInTheDocument()});
test('faq accordion works',async()=>{view();const q=screen.getByRole('button',{name:/Do I need to replace/});await userEvent.click(q);expect(screen.getByText(/Usually not/)).toBeInTheDocument()});
test('contact validation works',async()=>{view('/contact');await userEvent.click(screen.getByRole('button',{name:/Request a free consultation/}));expect(screen.getAllByText('This field is required.').length).toBeGreaterThan(0)});
test('published project page renders verification evidence',()=>{view('/workflows/buddyget-compatibility-matcher');expect(screen.getByRole('heading',{name:'BuddyGet Privacy-Aware Compatibility Matcher',level:1})).toBeInTheDocument();expect(screen.getByText(/Published in n8n and tested end to end/)).toBeInTheDocument()});
test('missing project shows useful 404',()=>{view('/workflows/missing');expect(screen.getByText(/could not be found/i)).toBeInTheDocument()});
test('published project does not show placeholder demo content',()=>{view('/workflows/job-application-tracker');expect(screen.queryByText('Automation demo coming soon')).not.toBeInTheDocument()});
