export type VideoType='youtube'|'loom'|'vimeo'|'mp4'|'none';
export interface Service{title:string;problem:string;solution:string;benefit:string}
export interface Project{slug:string;title:string;category:string;platform:string;summary:string;problem:string;manual:string;objective:string;steps:string[];preview:string[];tools:string[];impact:string[];status:string;evidence:string;video:{type:VideoType;url?:string};images:{src:string;alt:string;caption:string}[];industry:string;security:string[];securitySummary?:string;lessons:string[]}
export const profile={name:'Taiwo Fiyin',title:'AI Automation Specialist',location:'Ibadan, Nigeria',experience:'2 years',email:'hello@yourdomain.com',phone:'+234 000 000 0000',booking:'#contact',linkedin:'#',github:'#',whatsapp:'#'};
export const services:Service[]=[
 {title:'AI Workflow Automation',problem:'Repetitive operations and scattered data consume valuable team time.',solution:'I connect your tools and automate data movement, notifications, reporting, and approvals.',benefit:'Designed to lower administrative effort and give your team more capacity for valuable work.'},
 {title:'n8n Automation Development',problem:'Complex processes need more flexibility than basic one-step automations.',solution:'I build multi-step workflows with APIs, webhooks, databases, AI agents, and reliable business logic.',benefit:'A maintainable system shaped around how your business actually operates.'},
 {title:'Zapier Automation',problem:'Teams repeatedly copy information between everyday business applications.',solution:'I connect popular apps and create dependable triggers, actions, filters, and follow-ups.',benefit:'Can reduce manual entry, delays, and avoidable errors without replacing your current tools.'},
 {title:'AI Chatbots & Assistants',problem:'Customers and staff wait too long for answers to common questions.',solution:'I build assistants for qualification, support, booking, internal knowledge, and FAQs with human escalation.',benefit:'Faster, more consistent responses while people remain in control of sensitive cases.'},
 {title:'CRM & Lead Automation',problem:'Leads are missed, routed slowly, or followed up inconsistently.',solution:'I automate capture, qualification, assignment, reminders, and CRM updates.',benefit:'Designed to improve response speed and help sales teams focus on the right opportunities.'},
 {title:'Business Process Analysis',problem:'It is unclear which repetitive process is worth automating first.',solution:'I map current operations, bottlenecks, risks, handoffs, and high-impact opportunities.',benefit:'A practical automation roadmap based on business value—not technology for its own sake.'}
];
export const projects:Project[]=[
 {
  slug:'ts-car-clinic-feedback-automation',
  title:'TS Car Clinic — AI Feedback & Service Recovery',
  category:'Customer Experience',
  platform:'n8n + AI + Apps Script',
  summary:'A capstone system that connects completed car-care jobs to customer feedback, AI-assisted complaint triage, staff follow-up, and human-reviewed replies through one operations dashboard.',
  problem:'A car-care business with several branches needs to connect feedback to the right visit, spot serious or recurring complaints, give follow-up a clear owner, and keep customer replies accountable.',
  manual:'Track completed jobs in a spreadsheet, request feedback, match each response to a visit, read earlier complaints, notify the manager and responsible staff, draft a reply, and record the follow-up separately.',
  objective:'Build a complete feedback and service-recovery demo that combines useful AI analysis with explicit routing rules, staff ownership, reviewed communication, and a traceable case history.',
  steps:[
   'Create and complete a job in the Apps Script dashboard, with an optional staff owner from the same branch',
   'Send one authenticated completion event to n8n after the job state is saved',
   'Email a consented demo customer a feedback invitation that links the form to their visit automatically',
   'Validate the invitation and reject duplicate feedback before checking the customer’s complaint history',
   'Use local Ollama/Gemma to estimate sentiment and severity and prepare a specific response draft',
   'Apply explicit rules for positive, private, manager-escalation, or manual-review queues',
   'Record the case, notify the manager and eligible job owner on escalation, and assign follow-up separately',
   'Let staff edit and save the draft, then send only after explicit approval; record delivery and resolution in the activity log'
  ],
  preview:['Job completed','Linked customer feedback','AI triage + routing','Reviewed reply + follow-up'],
  tools:['n8n Cloud','Google Sheets','Google Apps Script','Ollama / Gemma','Gmail','Authenticated Webhooks','JavaScript'],
  impact:['Feedback linked to the correct service visit','Clearer ownership of complaint follow-up','Consistent escalation of serious or recurring complaints','Less repeated copying between inboxes and spreadsheets','Customer communication that remains under human control','A shared view of jobs, cases, and delivery history'],
  status:'Capstone · Validated demo',
  evidence:'The synthetic capstone demo was deployed and live-tested, with three published n8n workflows, three branches, and 18 synthetic staff. The 3 October 2026 release records 66 passing packaged checks and a tested invitation → linked feedback → escalation → approved reply flow. Production rollout is deferred; no customer-satisfaction, revenue, or time-saved results are claimed.',
  video:{type:'none'},
  images:[
   {src:'/workflows/ts-car-clinic-dashboard.png',alt:'TS Car Clinic demo operations dashboard showing job progress, manager alerts, cases to review, branch filtering, and staff navigation',caption:'Authentic deployed demo dashboard capture. The counts describe synthetic test records, not measured business outcomes.'},
   {src:'/workflows/ts-car-clinic-linked-feedback.png',alt:'TS Car Clinic customer feedback form with one feedback field and automatic visit linkage from the invitation email',caption:'Authentic published demo form: the invitation links the visit automatically, so the customer only enters their feedback.'}
  ],
  industry:'Automotive service operations',
  security:['Keep original feedback and send invalid or uncertain model analysis to manual review','Use explicit history and severity rules; AI scores and confidence are estimates, not calibrated safety measures','Saving a draft sends nothing; only a separately approved, saved reply can trigger customer email','Validate one consented demo recipient and branch-eligible staff before delivery','Preserve saved work on dispatch failures and guard retries; investigate uncertain sends before retrying','Keep public evidence free of customer contacts, private endpoints, and credentials'],
  securitySummary:'This is a synthetic demo using controlled inboxes. The shared dashboard requires a Google account but does not implement individual staff permissions or branch authorization. Production use needs verified roles, signed invitation links, a durable delivery ledger, model calibration, and continuously available inference. Credentials stay in private n8n/Google configuration; local model scoring depends on the operator’s PC and authenticated tunnel being available.',
  lessons:['Events tied to saved actions avoid spending n8n executions on idle polling','AI can help prioritize and draft, while explicit rules and staff approval keep decisions reviewable','The staff member who completed a job and the person handling a complaint need separate ownership fields','Hidden invitation IDs simplify the form but do not authenticate a customer','A successful demo is a useful engineering milestone, not proof of production readiness']
 },
 {slug:'buddyget-compatibility-matcher',title:'BuddyGet Privacy-Aware Compatibility Matcher',category:'BuddyGet',platform:'n8n + API',summary:'A scheduled matching workflow that scores compatible learners and writes auditable suggestions back to BuddyGet without sending contact details to n8n.',problem:'BuddyGet needs to compare learning profiles across skill, level, availability, time zone, goals, and commitment while respecting blocks, reports, and data-minimisation rules.',manual:'Review changed profiles, exclude unsafe pairings, compare multiple compatibility factors, explain each suggestion, store the result, and clear the processing queue.',objective:'Create a repeatable matching process with transparent scoring, protected application endpoints, and enough context for human review.',steps:['Run every 15 minutes','Load queued profiles through a protected BuddyGet endpoint','Score skill, level, availability, time zone, goals, and commitment','Exclude blocked, reported, or unsuitable pairs','Create readable match explanations','Store suggestions through the protected API','Acknowledge processed profile events'],preview:['15-minute schedule','Protected profile API','Compatibility scoring','Store suggestions'],tools:['n8n','JavaScript','Protected APIs','D1','Scheduled Trigger'],impact:['More consistent candidate evaluation','Less manual profile comparison','Traceable match explanations','Reduced risk of missed queue events','Data-minimised automation processing'],status:'Published · Active',evidence:'Published in n8n and tested end to end. Workflow status is verified; no user-growth, match-success, or time-saved metrics are claimed.',video:{type:'none'},images:[{src:'/workflows/buddyget-compatibility-matcher.png',alt:'n8n canvas showing the BuddyGet schedule, protected profile loading, compatibility scoring, and match suggestion nodes',caption:'Authentic n8n canvas captured from an inactive, credential-free preview of the published workflow layout.'}],industry:'Education technology',security:['Send matching fields only—never email, phone, exact location, or school','Use encrypted two-header credentials for the private-site and application gates','Exclude blocked and reported pairs before storing suggestions','Keep scoring logic and explanations auditable'],lessons:['Privacy boundaries are part of the workflow architecture, not an afterthought','A durable outbox makes scheduled retries safer','Deterministic criteria are easier to review than opaque matching claims']},
 {slug:'job-application-tracker',title:'Job Application Tracker & HR Routing',category:'HR Automation',platform:'n8n',summary:'An active recruitment workflow that receives form applications, classifies experience level, updates an applicant tracker, and coordinates candidate and HR emails.',problem:'Recruitment teams can lose time copying form responses, sorting applicants by experience, updating trackers, and sending several stages of email manually.',manual:'Read each application, standardise the details, decide an experience band, update a spreadsheet, notify HR, and send the appropriate candidate response.',objective:'Give every application a consistent processing path while keeping shortlisting decisions explicit and reviewable.',steps:['Detect a new Google Forms response in Sheets','Prepare and standardise applicant details','Route applicants through experience-level rules','Assign senior, mid-level, or entry-level classification','Save the applicant to the shared tracker','Send the applicant a confirmation email','Notify HR with the prepared details','Branch shortlisted candidates to interview or keep-on-file communication'],preview:['New application','Experience rules','Applicant tracker','Candidate + HR email'],tools:['n8n','Google Forms','Google Sheets','Gmail','Conditional Logic','Wait Nodes'],impact:['More consistent application handling','Less repetitive applicant data entry','Faster acknowledgement emails','Clearer HR routing','A traceable recruitment tracker'],status:'Published · Active',evidence:'The workflow is published and active in n8n. Its node structure and active status were verified; recruitment outcomes and time savings have not been measured.',video:{type:'none'},images:[{src:'/workflows/job-application-tracker.png',alt:'n8n canvas showing a Google Forms recruitment workflow with experience routing, applicant tracking, HR notifications, and candidate email branches',caption:'Authentic n8n canvas captured from an inactive, credential-free preview of the published workflow layout.'}],industry:'Recruitment operations',security:['Restrict access to applicant records and connected mailboxes','Keep experience rules visible instead of presenting them as AI judgment','Avoid sensitive attributes in automated screening criteria','Require HR ownership of final shortlisting decisions'],lessons:['Rule-based routing works best when criteria are explicit and legally reviewed','Candidate communication should remain consistent across every branch','Wait states need clear ownership and recovery paths']},
 {slug:'daily-ai-media-pipeline',title:'Daily AI Media Production Pipeline',category:'Content Automation',platform:'n8n + AI',summary:'A scheduled content workflow that turns a Google Sheets plan into structured copy and visual assets, stores outputs, updates the tracker, and sends delivery or error notifications.',problem:'Daily content production requires repeated handoffs between a content plan, copy generation, image creation, file storage, publishing tools, and status reporting.',manual:'Review the content calendar, write copy, prepare an image prompt, generate the asset, upload it, publish or distribute it, update the plan, and notify the operator when something fails.',objective:'Create one observable media pipeline that can prepare and route content consistently while keeping the source plan and generated assets traceable.',steps:['Start on a schedule or new Google Sheets item','Load the content guideline and planned post','Generate structured copy with a local Ollama model','Create a structured image prompt','Generate the visual through ComfyUI or the configured image service','Upload and share the asset through Google Drive','Publish through the configured social channel','Update the source row and send Telegram or WhatsApp notifications','Route failures to an operator alert'],preview:['Content schedule','AI copy + prompt','Generate + store media','Publish + notify'],tools:['n8n','Google Sheets','Ollama','ComfyUI','Google Drive','LinkedIn','Telegram','WhatsApp'],impact:['A repeatable daily publishing process','Fewer manual handoffs between content tools','Centralised source and status tracking','Reusable generated assets','Faster operator awareness when a branch fails'],status:'Published · Active',evidence:'The workflow is published and active in n8n. Connected nodes and error routing were verified; reach, engagement, and time-saved figures are not claimed.',video:{type:'none'},images:[{src:'/workflows/daily-ai-media-pipeline.png',alt:'Wide n8n canvas showing the connected scheduling, Google Sheets, AI generation, storage, publishing, messaging, and error-handling branches of the daily media workflow',caption:'Full n8n canvas captured from an inactive, credential-free preview; the wide view preserves the workflow’s multiple connected branches.'}],industry:'Content operations',security:['Keep social, messaging, and storage credentials encrypted in n8n','Review generated copy and media policy before unattended publishing','Avoid including private sheet data in prompts or notifications','Send actionable error messages without leaking credential or payload details'],lessons:['Structured outputs make multi-step AI workflows easier to validate','Content status should return to the source tracker','A dedicated error path is essential when several external services are involved']},
 {slug:'buddyget-weekly-d1-backup',title:'BuddyGet Weekly D1 Backup',category:'Data Protection',platform:'n8n + D1',summary:'A tested weekly workflow that downloads BuddyGet’s protected database export, converts it to a file, and writes it to persistent local backup storage.',problem:'A production application needs recoverable database copies that do not depend on a manual export being remembered every week.',manual:'Authenticate to the application, request the latest export, download it, name and save the file in the permitted backup path, and confirm it is included in the wider encrypted archive process.',objective:'Create a scheduled, repeatable first stage for BuddyGet database recovery with a manual test trigger and protected export access.',steps:['Run every Sunday at 2 AM or from the manual test trigger','Download the protected D1 export from BuddyGet','Convert the export response into a file','Write the file to n8n’s persistent backup mount','Include the folder in the encrypted weekly archive and second-disk mirror','Review backup logs and recovery readiness'],preview:['Weekly schedule','Protected D1 export','Convert to file','Persistent backup'],tools:['n8n','Cloudflare D1','Protected API','Persistent Storage','Encrypted Archive'],impact:['More consistent backup cadence','Reduced dependence on manual exports','A recoverable local database copy','Clearer recovery operations','Separation between export access and encrypted archive storage'],status:'Published · Active · Tested',evidence:'The workflow is published, active, and tested end to end. The first verified export contained all 11 BuddyGet D1 tables; restore readiness still depends on the wider documented recovery process.',video:{type:'none'},images:[{src:'/workflows/buddyget-weekly-d1-backup.png',alt:'n8n canvas showing the scheduled and manual BuddyGet backup triggers, protected D1 export, file conversion, and persistent storage nodes',caption:'Authentic n8n canvas captured from an inactive, credential-free preview of the published workflow layout.'}],industry:'Application operations',security:['Protect the export endpoint with least-privilege encrypted credentials','Write only to n8n’s permitted persistent backup directory','Keep archive keys outside workflow JSON, source control, and Obsidian','Test restoration separately from successful file creation'],lessons:['A successful export is not the same as a successful restore','Backup storage must survive container replacement','Manual test triggers make scheduled recovery workflows easier to validate']}
];
export const faqs=[
 ['What types of businesses can benefit from AI automation?','Any business with repeated digital tasks, frequent handoffs, growing enquiry volume, or scattered information may benefit. The strongest opportunities are stable, high-frequency processes.'],
 ['What business processes can be automated?','Lead capture, follow-up, customer support, reporting, notifications, data entry, approvals, scheduling, and many cross-application workflows.'],
 ['Do I need to replace my existing tools?','Usually not. I first look for safe ways to connect and improve the tools your team already knows.'],
 ['What is the difference between n8n and Zapier?','Zapier is quick and accessible for many common app connections. n8n offers more flexibility for complex logic, APIs, data handling, and custom deployment needs.'],
 ['Can AI automation work with my CRM?','Often, yes. If your CRM provides a supported integration or API, workflows can capture, update, route, and follow up with records.'],
 ['How long does an automation project usually take?','A focused workflow may take days; a multi-system process can take several weeks. Timing depends on access, complexity, testing, and safeguards.'],
 ['Will my team still have control over the workflow?','Yes. I design clear checkpoints, approvals, logs, and escalation paths wherever human judgment is important.'],
 ['What happens if an automation fails?','Good workflows validate inputs, retry safe actions, log errors, alert an owner, and provide a manual recovery path.'],
 ['Can you maintain and improve the workflow after launch?','Yes. Monitoring, documentation, and ongoing improvements can be included in the engagement.'],
 ['How do we identify the best process to automate first?','We compare repetition, time cost, error rate, business impact, technical feasibility, and risk—then start with a practical high-value opportunity.']
];
export const testimonials=[{quote:'Client testimonial coming soon.',name:'Verified client feedback will appear here.'},{quote:'Client testimonial coming soon.',name:'No invented names or claims.'}];
