export type VideoType='youtube'|'loom'|'vimeo'|'mp4'|'none';
export interface Service{title:string;problem:string;solution:string;benefit:string}
export interface Project{slug:string;title:string;category:string;platform:string;summary:string;problem:string;manual:string;objective:string;steps:string[];tools:string[];impact:string[];status:string;video:{type:VideoType;url?:string};images:{src:string;alt:string;caption:string}[];industry:string;security:string[];lessons:string[]}
export const profile={name:'Taiwo Oloni',title:'AI Automation Specialist',location:'Ibadan, Nigeria',experience:'2 years',email:'hello@yourdomain.com',phone:'+234 000 000 0000',booking:'#contact',linkedin:'#',github:'#',whatsapp:'#'};
export const services:Service[]=[
 {title:'AI Workflow Automation',problem:'Repetitive operations and scattered data consume valuable team time.',solution:'I connect your tools and automate data movement, notifications, reporting, and approvals.',benefit:'Designed to lower administrative effort and give your team more capacity for valuable work.'},
 {title:'n8n Automation Development',problem:'Complex processes need more flexibility than basic one-step automations.',solution:'I build multi-step workflows with APIs, webhooks, databases, AI agents, and reliable business logic.',benefit:'A maintainable system shaped around how your business actually operates.'},
 {title:'Zapier Automation',problem:'Teams repeatedly copy information between everyday business applications.',solution:'I connect popular apps and create dependable triggers, actions, filters, and follow-ups.',benefit:'Can reduce manual entry, delays, and avoidable errors without replacing your current tools.'},
 {title:'AI Chatbots & Assistants',problem:'Customers and staff wait too long for answers to common questions.',solution:'I build assistants for qualification, support, booking, internal knowledge, and FAQs with human escalation.',benefit:'Faster, more consistent responses while people remain in control of sensitive cases.'},
 {title:'CRM & Lead Automation',problem:'Leads are missed, routed slowly, or followed up inconsistently.',solution:'I automate capture, qualification, assignment, reminders, and CRM updates.',benefit:'Designed to improve response speed and help sales teams focus on the right opportunities.'},
 {title:'Business Process Analysis',problem:'It is unclear which repetitive process is worth automating first.',solution:'I map current operations, bottlenecks, risks, handoffs, and high-impact opportunities.',benefit:'A practical automation roadmap based on business value—not technology for its own sake.'}
];
const image=(name:string)=>[{src:'/workflow-placeholder.svg',alt:`Editable placeholder for ${name} workflow screenshot`,caption:'Placeholder — replace with an exported workflow screenshot.'}];
export const projects:Project[]=[
 {slug:'ai-lead-qualification',title:'AI Lead Qualification & Follow-Up',category:'Lead Automation',platform:'n8n',summary:'A structured lead pipeline that captures, evaluates, routes, and follows up with every inquiry.',problem:'Incoming leads arrive from several channels, but staff must manually review and follow up with each one.',manual:'Copy lead details, interpret intent, choose an owner, send an acknowledgement, and remember follow-ups.',objective:'Create a consistent first response and give salespeople useful context without removing human judgment.',steps:['Capture the form or webhook','Validate and clean lead data','Classify intent and urgency with AI','Assign a transparent lead score','Save to a CRM or Google Sheet','Send a personalised acknowledgement','Notify the right salesperson in Slack','Schedule follow-up reminders'],tools:['n8n','OpenAI','Gmail','Google Sheets','Slack','Webhooks'],impact:['Faster lead response','Reduced manual data entry','Better lead prioritisation','Improved sales-team capacity','Lower risk of missed opportunities'],status:'Editable sample case study',video:{type:'none'},images:image('lead qualification'),industry:'Service business (placeholder)',security:['Validate all incoming fields','Limit access to lead data','Keep a human checkpoint for high-value decisions'],lessons:['Keep scoring criteria visible to sales teams','Design fallbacks before adding AI classification']},
 {slug:'ai-customer-support',title:'AI Customer Support Assistant',category:'Customer Support',platform:'Zapier / n8n',summary:'A human-aware support assistant that drafts grounded answers and escalates the cases that need care.',problem:'A support team spends too much time answering the same customer questions.',manual:'Read each message, search internal guidance, write a response, escalate uncertain cases, and record the outcome.',objective:'Speed up routine support while protecting quality with approved knowledge and human escalation.',steps:['Receive the customer inquiry','Categorise the request','Search the approved knowledge base','Draft a grounded response','Escalate sensitive or complex cases','Record the inquiry for reporting','Notify support when intervention is required'],tools:['OpenAI','n8n','Zapier','Knowledge base','Gmail','Slack'],impact:['Faster response times','Reduced repetitive workload','More consistent answers','Improved customer experience','Better support reporting'],status:'Editable sample case study',video:{type:'none'},images:image('customer support'),industry:'Customer service team (placeholder)',security:['Use only approved knowledge sources','Never auto-send sensitive answers','Log escalations and access'],lessons:['A clear confidence threshold is essential','Human ownership must always be visible']},
 {slug:'automated-business-reporting',title:'Automated Business Reporting',category:'Internal Operations',platform:'n8n',summary:'A weekly reporting system that unifies operational data and turns it into a clear stakeholder briefing.',problem:'Managers spend hours gathering information from several applications and preparing weekly reports.',manual:'Export data, clean spreadsheets, calculate indicators, write a summary, and distribute it to stakeholders.',objective:'Create a repeatable reporting rhythm with traceable calculations and a concise AI-assisted narrative.',steps:['Pull data from connected tools','Clean and combine the data','Calculate agreed performance indicators','Summarise material changes with AI','Generate the weekly report','Email stakeholders','Post a condensed Slack summary'],tools:['n8n','Google Sheets','Airtable','OpenAI','Gmail','Slack','APIs'],impact:['Less report preparation time','More consistent reporting','Faster access to insights','Better-informed decisions','Reduced administrative workload'],status:'Editable sample case study',video:{type:'none'},images:image('business reporting'),industry:'Operations team (placeholder)',security:['Use least-privilege API access','Separate calculations from AI summaries','Retain source links for review'],lessons:['Agree KPI definitions before building','Make every summary traceable to source data']}
];
export const faqs=[
 ['What types of businesses can benefit from AI automation?','Any business with repeated digital tasks, frequent handoffs, growing enquiry volume, or scattered information may benefit. The strongest opportunities are stable, high-frequency processes.'],
 ['What business processes can be automated?','Lead capture, follow-up, customer support, reporting, notifications, data entry, approvals, scheduling, and many cross-application workflows.'],
 ['Do I need to replace my existing tools?','Usually not. I first look for safe ways to connect and improve the tools your team already knows.'],
 ['What is the difference between n8n and Zapier?','Zapier is quick and accessible for many common app connections. n8n offers more flexibility for complex logic, APIs, data handling, and custom deployment needs.'],
 ['Can AI automation work with my CRM?','Often, yes. If your CRM provides a supported integration or API, workflows can capture, update, route, and follow up with records.'],
 ['How long does an automation project usually take?','A focused workflow may take days; a multi-system process can take several weeks. Timing depends on access, complexity, testing, and safeguards.'],
 ['Will my team still have control over the workflow?','Yes. I design clear checkpoints, approvals, logs, and escalation paths wherever human judgment is important.'],
 ['What happens if an automation fails?','Good workflows validate inputs, retry safe actions, log errors, alert an owner, and provide a manual recovery path.'],
 ['Can you maintain and improve the workflow after launch?','Yes. Monitoring, documentation, and ongoing improvements can be included in the engagement.'],
 ['How do we identify the best process to automate first?','We compare repetition, time cost, error rate, business impact, technical feasibility, and risk—then start with a practical high-value opportunity.']
];
export const testimonials=[{quote:'Client testimonial coming soon.',name:'Verified client feedback will appear here.'},{quote:'Client testimonial coming soon.',name:'No invented names or claims.'}];
